# Generated by Django 4.1.2 on 2023-06-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre_prod', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('precio_prod', models.IntegerField(verbose_name='Precio Producto')),
                ('img_prod', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('email_usuario', models.CharField(max_length=50, verbose_name='Email')),
                ('contraseña_usuario', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('desc_compra', models.CharField(default='', max_length=1000, verbose_name='Descripción compra')),
                ('id_prod', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='alumnos.producto', verbose_name='Id Producto')),
                ('id_usuario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='alumnos.usuario', verbose_name='Id Usuario')),
            ],
        ),
    ]
